
export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const FETCH_STUDENTS_START = 'FETCH_STUDENTS_START';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAIL = 'FETCH_STUDENTS_FAIL';

export const FETCH_STUDENT = 'FETCH_STUDENT';
export const FETCH_STUDENT_START = 'FETCH_STUDENT_START';
export const FETCH_STUDENT_SUCCESS = 'FETCH_STUDENT_SUCCESS';
export const FETCH_STUDENT_FAIL = 'FETCH_STUDENT_FAIL';

export const CREATE_STUDENT = 'CREATE_STUDENT';
export const CREATE_STUDENT_START = 'CREATE_STUDENT_START';
export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS';
export const CREATE_STUDENT_FAIL = 'CREATE_STUDENT_FAIL';

export const DELETE_STUDENT = 'DELETE_STUDENT';
export const DELETE_STUDENT_START = 'DELETE_STUDENT_START';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
export const DELETE_STUDENT_FAIL = 'DELETE_STUDENT_FAIL';

export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const UPDATE_STUDENT_START = 'UPDATE_STUDENT_START';
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS';
export const UPDATE_STUDENT_FAIL = 'UPDATE_STUDENT_FAIL';


export const ADD_TEACHER = 'ADD_TEACHER';
export const REMOVE_TEACHER = 'REMOVE_TEACHER';

export const ADD_RESOURCE = 'ADD_RESOURCE';
export const REMOVE_RESOURCE = 'REMOVE_RESOURCE';

export const ADD_LESSON = 'ADD_LESSON';
export const REMOVE_LESSON = 'REMOVE_LESSON';